/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBlocklist, IBlocklistInterface } from "../IBlocklist";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "isBlocked",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IBlocklist__factory {
  static readonly abi = _abi;
  static createInterface(): IBlocklistInterface {
    return new utils.Interface(_abi) as IBlocklistInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBlocklist {
    return new Contract(address, _abi, signerOrProvider) as IBlocklist;
  }
}
