/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IGuardedInterface extends ethers.utils.Interface {
  functions: {
    "ANY_CALLER()": FunctionFragment;
    "ANY_SIG()": FunctionFragment;
    "allowCaller(bytes32,address)": FunctionFragment;
    "blockCaller(bytes32,address)": FunctionFragment;
    "canCall(bytes32,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ANY_CALLER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ANY_SIG", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allowCaller",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "blockCaller",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "canCall",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(functionFragment: "ANY_CALLER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ANY_SIG", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canCall", data: BytesLike): Result;

  events: {};
}

export class IGuarded extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IGuardedInterface;

  functions: {
    ANY_CALLER(overrides?: CallOverrides): Promise<[string]>;

    ANY_SIG(overrides?: CallOverrides): Promise<[string]>;

    allowCaller(
      sig: BytesLike,
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    blockCaller(
      sig: BytesLike,
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    canCall(
      sig: BytesLike,
      who: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  ANY_CALLER(overrides?: CallOverrides): Promise<string>;

  ANY_SIG(overrides?: CallOverrides): Promise<string>;

  allowCaller(
    sig: BytesLike,
    who: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  blockCaller(
    sig: BytesLike,
    who: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  canCall(
    sig: BytesLike,
    who: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    ANY_CALLER(overrides?: CallOverrides): Promise<string>;

    ANY_SIG(overrides?: CallOverrides): Promise<string>;

    allowCaller(
      sig: BytesLike,
      who: string,
      overrides?: CallOverrides
    ): Promise<void>;

    blockCaller(
      sig: BytesLike,
      who: string,
      overrides?: CallOverrides
    ): Promise<void>;

    canCall(
      sig: BytesLike,
      who: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    ANY_CALLER(overrides?: CallOverrides): Promise<BigNumber>;

    ANY_SIG(overrides?: CallOverrides): Promise<BigNumber>;

    allowCaller(
      sig: BytesLike,
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    blockCaller(
      sig: BytesLike,
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    canCall(
      sig: BytesLike,
      who: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ANY_CALLER(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ANY_SIG(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allowCaller(
      sig: BytesLike,
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    blockCaller(
      sig: BytesLike,
      who: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    canCall(
      sig: BytesLike,
      who: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
